#!/usr/bin/env bash

if
  [[ -s "foo/environment" ]]
then
  source "foo/environment"
  exec executable-hooks-uninstaller "$@"
else
  echo "ERROR: Missing RVM environment file: 'foo/environment'" >&2
  exit 1
fi
