name: Deploy Backend SIP
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend Rails app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}

          script: |
            cd backend-crm-sipca
            git pull origin master
            bundle exec rails db:migrate
            bundle exec rails db:seed
            echo 'Deploy Successful to digital ocean'
